spring:
  application:
    name: project_gm
  profiles:
    default: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

server:
  servlet:
    context-path: /project_gm
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
